name: goreleaser

on:
  push:
    tags:
      - '*'

permissions:
  contents: write
  packages: write

jobs:
  goreleaser:
    runs-on: ubuntu-20.04
    steps:
      -
        name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      -
        name: Fetch all tags
        run: git fetch --force --tags
      -
        name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: '>=1.20.2'
          cache: true
      -
        name: Run GoReleaser
        uses: goreleaser/goreleaser-action@v4
        with:
          distribution: goreleaser
          version: latest
          args: build --clean
      -
        name: Install wash 
        uses: wasmcloud/common-actions/install-wash@main
      -
        name: Create Providers
        env:
          WASH_ISSUER_KEY: ${{ secrets.WASH_ISSUER_KEY }}
          WASH_SUBJECT_KEY: ${{ secrets.WASH_SUBJECT_KEY }}
        run: |
          wash par create --arch x86_64-macos   --binary dist/tsnet-httpserver_darwin_amd64_v1/tsnet-httpserver --capid wasmcloud:httpserver --name "Tailscale HTTPServer (Go)" --vendor jordan-rash --version ${{ github.ref_name }} --revision 1 --destination dist/provider.par.gz
          wash par insert --arch aarch64-macos  --binary dist/tsnet-httpserver_darwin_arm64/tsnet-httpserver   dist/provider.par.gz
          wash par insert --arch x86_64-linux   --binary dist/tsnet-httpserver_linux_amd64_v1/tsnet-httpserver dist/provider.par.gz
          wash par insert --arch aarch64-linux  --binary dist/tsnet-httpserver_linux_arm64/tsnet-httpserver    dist/provider.par.gz
      - name: Upload provider archive to GH Actions
        env:
          WASH_REG_USER: jordan-rash
          WASH_REG_PASSWORD: ${{ secrets.WASH_PAT }}
        run: |
          wash reg push ghcr.io/jordan-rash/tsnet-httpserver:${{ github.ref_name }} dist/provider.par.gz -a org.opencontainers.image.source=https://github.com/jordan-rash/tsnet-httpserver -a org.opencontainers.image.description="Tailscale HTTPServer Provider (Go)"

